version: '3'

services:
  postgres:
    image: postgres:13.7
    command: postgres -c 'max_connections=300'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"  # Changed from 5436 to 5432
    networks:
      - keycloak_network
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev
    environment:
      # Admin Credentials
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: admin
      KC_DB_USERNAME: admin
      KC_HTTPS_REQUIRED: 'false'
      KC_HTTP_ENABLED: 'true'
      KEYCLOAK_HTTP_SSL_REQUIRED: none
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - keycloak_network

volumes:
  pgdata:

networks:
  keycloak_network:
    driver: bridge
