version: '3'

services:
  postgres:
    image: postgres:13.7
    command: postgres -c 'max_connections=300'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: "exit 0"
    ports:
      - 5436:5436
    networks:
      - keycloak_network
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev sslRequired=NONE
    environment:
      #Admin Credentials
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: admin
      KC_DB_USERNAME: admin
      KEYCLOAK_HTTP_SSL_REQUIRED: none
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DB_SHCHEMA: public
    ports:
      - 80:8080
    depends_on:
      - postgres
    networks:
      - keycloak_network

volumes:
  pgdata:

networks:
  keycloak_network:
    driver: bridge
